Search.appendIndex(
    [
                {
            "fqsen": "\\ZnCore\\Contract\\Arr\\Interfaces\\ToArrayInterface",
            "name": "ToArrayInterface",
            "summary": "",
            "url": "classes/ZnCore-Contract-Arr-Interfaces-ToArrayInterface.html"
        },                {
            "fqsen": "\\ZnCore\\Contract\\Arr\\Interfaces\\ToArrayInterface\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "",
            "url": "classes/ZnCore-Contract-Arr-Interfaces-ToArrayInterface.html#method_toArray"
        },                {
            "fqsen": "\\ZnCore\\Contract\\Common\\Exceptions\\DisabledException",
            "name": "DisabledException",
            "summary": "",
            "url": "classes/ZnCore-Contract-Common-Exceptions-DisabledException.html"
        },                {
            "fqsen": "\\ZnCore\\Contract\\Domain\\Interfaces\\DataProviderInterface",
            "name": "DataProviderInterface",
            "summary": "",
            "url": "classes/ZnCore-Contract-Domain-Interfaces-DataProviderInterface.html"
        },                {
            "fqsen": "\\ZnCore\\Contract\\Domain\\Interfaces\\DataProviderInterface\u003A\u003AgetCollection\u0028\u0029",
            "name": "getCollection",
            "summary": "",
            "url": "classes/ZnCore-Contract-Domain-Interfaces-DataProviderInterface.html#method_getCollection"
        },                {
            "fqsen": "\\ZnCore\\Contract\\Domain\\Interfaces\\DataProviderInterface\u003A\u003AgetTotalCount\u0028\u0029",
            "name": "getTotalCount",
            "summary": "",
            "url": "classes/ZnCore-Contract-Domain-Interfaces-DataProviderInterface.html#method_getTotalCount"
        },                {
            "fqsen": "\\ZnCore\\Contract\\Domain\\Interfaces\\Entities\\EntityIdInterface",
            "name": "EntityIdInterface",
            "summary": "",
            "url": "classes/ZnCore-Contract-Domain-Interfaces-Entities-EntityIdInterface.html"
        },                {
            "fqsen": "\\ZnCore\\Contract\\Domain\\Interfaces\\Entities\\EntityIdInterface\u003A\u003AsetId\u0028\u0029",
            "name": "setId",
            "summary": "",
            "url": "classes/ZnCore-Contract-Domain-Interfaces-Entities-EntityIdInterface.html#method_setId"
        },                {
            "fqsen": "\\ZnCore\\Contract\\Domain\\Interfaces\\Entities\\EntityIdInterface\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/ZnCore-Contract-Domain-Interfaces-Entities-EntityIdInterface.html#method_getId"
        },                {
            "fqsen": "\\ZnCore\\Contract\\Domain\\Interfaces\\ForgeQueryByFilterInterface",
            "name": "ForgeQueryByFilterInterface",
            "summary": "",
            "url": "classes/ZnCore-Contract-Domain-Interfaces-ForgeQueryByFilterInterface.html"
        },                {
            "fqsen": "\\ZnCore\\Contract\\Domain\\Interfaces\\ForgeQueryByFilterInterface\u003A\u003AforgeQueryByFilter\u0028\u0029",
            "name": "forgeQueryByFilter",
            "summary": "",
            "url": "classes/ZnCore-Contract-Domain-Interfaces-ForgeQueryByFilterInterface.html#method_forgeQueryByFilter"
        },                {
            "fqsen": "\\ZnCore\\Contract\\Encoder\\Interfaces\\EncoderInterface",
            "name": "EncoderInterface",
            "summary": "",
            "url": "classes/ZnCore-Contract-Encoder-Interfaces-EncoderInterface.html"
        },                {
            "fqsen": "\\ZnCore\\Contract\\Encoder\\Interfaces\\EncoderInterface\u003A\u003Aencode\u0028\u0029",
            "name": "encode",
            "summary": "",
            "url": "classes/ZnCore-Contract-Encoder-Interfaces-EncoderInterface.html#method_encode"
        },                {
            "fqsen": "\\ZnCore\\Contract\\Encoder\\Interfaces\\EncoderInterface\u003A\u003Adecode\u0028\u0029",
            "name": "decode",
            "summary": "",
            "url": "classes/ZnCore-Contract-Encoder-Interfaces-EncoderInterface.html#method_decode"
        },                {
            "fqsen": "\\ZnCore\\Contract\\Encoder\\Interfaces\\PrettifyInterface",
            "name": "PrettifyInterface",
            "summary": "",
            "url": "classes/ZnCore-Contract-Encoder-Interfaces-PrettifyInterface.html"
        },                {
            "fqsen": "\\ZnCore\\Contract\\Encoder\\Interfaces\\PrettifyInterface\u003A\u003Aprettify\u0028\u0029",
            "name": "prettify",
            "summary": "",
            "url": "classes/ZnCore-Contract-Encoder-Interfaces-PrettifyInterface.html#method_prettify"
        },                {
            "fqsen": "\\ZnCore\\Contract\\Enum\\Interfaces\\GetLabelsInterface",
            "name": "GetLabelsInterface",
            "summary": "",
            "url": "classes/ZnCore-Contract-Enum-Interfaces-GetLabelsInterface.html"
        },                {
            "fqsen": "\\ZnCore\\Contract\\Enum\\Interfaces\\GetLabelsInterface\u003A\u003AgetLabels\u0028\u0029",
            "name": "getLabels",
            "summary": "",
            "url": "classes/ZnCore-Contract-Enum-Interfaces-GetLabelsInterface.html#method_getLabels"
        },                {
            "fqsen": "\\ZnCore\\Contract\\Kernel\\Interfaces\\KernelInterface",
            "name": "KernelInterface",
            "summary": "",
            "url": "classes/ZnCore-Contract-Kernel-Interfaces-KernelInterface.html"
        },                {
            "fqsen": "\\ZnCore\\Contract\\Kernel\\Interfaces\\KernelInterface\u003A\u003AloadAppConfig\u0028\u0029",
            "name": "loadAppConfig",
            "summary": "",
            "url": "classes/ZnCore-Contract-Kernel-Interfaces-KernelInterface.html#method_loadAppConfig"
        },                {
            "fqsen": "\\ZnCore\\Contract\\Mapper\\Interfaces\\MapperInterface",
            "name": "MapperInterface",
            "summary": "Interface\u0020MapperInterface",
            "url": "classes/ZnCore-Contract-Mapper-Interfaces-MapperInterface.html"
        },                {
            "fqsen": "\\ZnCore\\Contract\\Rbac\\Interfaces\\GetRbacInheritanceInterface",
            "name": "GetRbacInheritanceInterface",
            "summary": "",
            "url": "classes/ZnCore-Contract-Rbac-Interfaces-GetRbacInheritanceInterface.html"
        },                {
            "fqsen": "\\ZnCore\\Contract\\Rbac\\Interfaces\\GetRbacInheritanceInterface\u003A\u003AgetInheritance\u0028\u0029",
            "name": "getInheritance",
            "summary": "",
            "url": "classes/ZnCore-Contract-Rbac-Interfaces-GetRbacInheritanceInterface.html#method_getInheritance"
        },                {
            "fqsen": "\\ZnCore\\Contract\\Rbac\\Traits\\CrudRbacInheritanceTrait",
            "name": "CrudRbacInheritanceTrait",
            "summary": "",
            "url": "classes/ZnCore-Contract-Rbac-Traits-CrudRbacInheritanceTrait.html"
        },                {
            "fqsen": "\\ZnCore\\Contract\\Rbac\\Traits\\CrudRbacInheritanceTrait\u003A\u003AgetInheritance\u0028\u0029",
            "name": "getInheritance",
            "summary": "",
            "url": "classes/ZnCore-Contract-Rbac-Traits-CrudRbacInheritanceTrait.html#method_getInheritance"
        },                {
            "fqsen": "\\ZnCore\\Contract\\User\\Exceptions\\ForbiddenException",
            "name": "ForbiddenException",
            "summary": "",
            "url": "classes/ZnCore-Contract-User-Exceptions-ForbiddenException.html"
        },                {
            "fqsen": "\\ZnCore\\Contract\\User\\Exceptions\\UnauthorizedException",
            "name": "UnauthorizedException",
            "summary": "",
            "url": "classes/ZnCore-Contract-User-Exceptions-UnauthorizedException.html"
        },                {
            "fqsen": "\\ZnCore\\Contract\\User\\Interfaces\\Entities\\IdentityEntityInterface",
            "name": "IdentityEntityInterface",
            "summary": "",
            "url": "classes/ZnCore-Contract-User-Interfaces-Entities-IdentityEntityInterface.html"
        },                {
            "fqsen": "\\ZnCore\\Contract\\User\\Traits\\GetUserTrait",
            "name": "GetUserTrait",
            "summary": "",
            "url": "classes/ZnCore-Contract-User-Traits-GetUserTrait.html"
        },                {
            "fqsen": "\\ZnCore\\Contract\\User\\Traits\\GetUserTrait\u003A\u003AgetUser\u0028\u0029",
            "name": "getUser",
            "summary": "",
            "url": "classes/ZnCore-Contract-User-Traits-GetUserTrait.html#method_getUser"
        },                {
            "fqsen": "\\ZnCore\\Contract\\User\\Traits\\GetUserTrait\u003A\u003AsetSecurity\u0028\u0029",
            "name": "setSecurity",
            "summary": "",
            "url": "classes/ZnCore-Contract-User-Traits-GetUserTrait.html#method_setSecurity"
        },                {
            "fqsen": "\\ZnCore\\Contract\\User\\Traits\\GetUserTrait\u003A\u003A\u0024user",
            "name": "user",
            "summary": "",
            "url": "classes/ZnCore-Contract-User-Traits-GetUserTrait.html#property_user"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\ZnCore\\Contract\\Arr\\Interfaces",
            "name": "Interfaces",
            "summary": "",
            "url": "namespaces/zncore-contract-arr-interfaces.html"
        },                {
            "fqsen": "\\ZnCore\\Contract\\Arr",
            "name": "Arr",
            "summary": "",
            "url": "namespaces/zncore-contract-arr.html"
        },                {
            "fqsen": "\\ZnCore\\Contract",
            "name": "Contract",
            "summary": "",
            "url": "namespaces/zncore-contract.html"
        },                {
            "fqsen": "\\ZnCore",
            "name": "ZnCore",
            "summary": "",
            "url": "namespaces/zncore.html"
        },                {
            "fqsen": "\\ZnCore\\Contract\\Common\\Exceptions",
            "name": "Exceptions",
            "summary": "",
            "url": "namespaces/zncore-contract-common-exceptions.html"
        },                {
            "fqsen": "\\ZnCore\\Contract\\Common",
            "name": "Common",
            "summary": "",
            "url": "namespaces/zncore-contract-common.html"
        },                {
            "fqsen": "\\ZnCore\\Contract\\Domain\\Interfaces",
            "name": "Interfaces",
            "summary": "",
            "url": "namespaces/zncore-contract-domain-interfaces.html"
        },                {
            "fqsen": "\\ZnCore\\Contract\\Domain",
            "name": "Domain",
            "summary": "",
            "url": "namespaces/zncore-contract-domain.html"
        },                {
            "fqsen": "\\ZnCore\\Contract\\Domain\\Interfaces\\Entities",
            "name": "Entities",
            "summary": "",
            "url": "namespaces/zncore-contract-domain-interfaces-entities.html"
        },                {
            "fqsen": "\\ZnCore\\Contract\\Encoder\\Interfaces",
            "name": "Interfaces",
            "summary": "",
            "url": "namespaces/zncore-contract-encoder-interfaces.html"
        },                {
            "fqsen": "\\ZnCore\\Contract\\Encoder",
            "name": "Encoder",
            "summary": "",
            "url": "namespaces/zncore-contract-encoder.html"
        },                {
            "fqsen": "\\ZnCore\\Contract\\Enum\\Interfaces",
            "name": "Interfaces",
            "summary": "",
            "url": "namespaces/zncore-contract-enum-interfaces.html"
        },                {
            "fqsen": "\\ZnCore\\Contract\\Enum",
            "name": "Enum",
            "summary": "",
            "url": "namespaces/zncore-contract-enum.html"
        },                {
            "fqsen": "\\ZnCore\\Contract\\Kernel\\Interfaces",
            "name": "Interfaces",
            "summary": "",
            "url": "namespaces/zncore-contract-kernel-interfaces.html"
        },                {
            "fqsen": "\\ZnCore\\Contract\\Kernel",
            "name": "Kernel",
            "summary": "",
            "url": "namespaces/zncore-contract-kernel.html"
        },                {
            "fqsen": "\\ZnCore\\Contract\\Mapper\\Interfaces",
            "name": "Interfaces",
            "summary": "",
            "url": "namespaces/zncore-contract-mapper-interfaces.html"
        },                {
            "fqsen": "\\ZnCore\\Contract\\Mapper",
            "name": "Mapper",
            "summary": "",
            "url": "namespaces/zncore-contract-mapper.html"
        },                {
            "fqsen": "\\ZnCore\\Contract\\Rbac\\Interfaces",
            "name": "Interfaces",
            "summary": "",
            "url": "namespaces/zncore-contract-rbac-interfaces.html"
        },                {
            "fqsen": "\\ZnCore\\Contract\\Rbac",
            "name": "Rbac",
            "summary": "",
            "url": "namespaces/zncore-contract-rbac.html"
        },                {
            "fqsen": "\\ZnCore\\Contract\\Rbac\\Traits",
            "name": "Traits",
            "summary": "",
            "url": "namespaces/zncore-contract-rbac-traits.html"
        },                {
            "fqsen": "\\ZnCore\\Contract\\User\\Exceptions",
            "name": "Exceptions",
            "summary": "",
            "url": "namespaces/zncore-contract-user-exceptions.html"
        },                {
            "fqsen": "\\ZnCore\\Contract\\User",
            "name": "User",
            "summary": "",
            "url": "namespaces/zncore-contract-user.html"
        },                {
            "fqsen": "\\ZnCore\\Contract\\User\\Interfaces\\Entities",
            "name": "Entities",
            "summary": "",
            "url": "namespaces/zncore-contract-user-interfaces-entities.html"
        },                {
            "fqsen": "\\ZnCore\\Contract\\User\\Interfaces",
            "name": "Interfaces",
            "summary": "",
            "url": "namespaces/zncore-contract-user-interfaces.html"
        },                {
            "fqsen": "\\ZnCore\\Contract\\User\\Traits",
            "name": "Traits",
            "summary": "",
            "url": "namespaces/zncore-contract-user-traits.html"
        }            ]
);
